language: php
sudo: false
php:
  - '5.6'
  - '7.0'
  - '7.1'

before_install:
  - echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "swoole.use_namespace = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - pecl install -f swoole-1.8.2.tgz
  - travis_retry composer self-update

install:
  composer install --no-interaction --prefer-dist --no-suggest

script: vendor/bin/phpunit
